#!/bin/bash

# Cluster completely unconfigured.  Generate config json and load on first node
id=0
host_array=()
for ip in ${current_ips} ; do
  host_array+=("{ \"_id\": ${id}, \"host\":\"${ip}\" }")
  id=$(($id + 1))
done
host_json=$(join , "${host_array[@]}")
config_json="{ \"_id\": \"${MONGODB_REPLSET}\", \"members\": [ ${host_json} ]}"
clean_json=$(echo ${config_json} | jq -c .)
echo $clean_json
echo "rs.reconfig($clean_json,{force: true})" | /usr/bin/mongo ${primary_ip} --quiet
